import { defineField, defineType } from "sanity";

export const projectType = defineType({
  name: "project",
  title: "作品",
  type: "document",
  fields: [
    defineField({
      name: "title",
      title: "作品名稱",
      type: "string",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "slug",
      title: "作品網址",
      description: "會用在前台網址，例如 portrait-study 會產生 /gallery/portrait-study。",
      type: "slug",
      options: { source: "title", maxLength: 96 },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "coverImage",
      title: "封面圖片",
      description: "會顯示在 Gallery 列表，也可用於首頁輪播。",
      type: "image",
      options: { hotspot: true },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "galleryImages",
      title: "作品圖片",
      description: "進入作品頁後顯示的完整照片列表。",
      type: "array",
      of: [{ type: "image", options: { hotspot: true } }],
    }),
    defineField({
      name: "categories",
      title: "分類",
      description: "可以選擇一個或多個分類。",
      type: "array",
      of: [{ type: "reference", to: [{ type: "category" }] }],
    }),
    defineField({
      name: "description",
      title: "作品介紹",
      type: "text",
      rows: 5,
    }),
    defineField({
      name: "shootingDate",
      title: "拍攝日期",
      type: "date",
    }),
    defineField({
      name: "location",
      title: "拍攝地點",
      type: "string",
    }),
    defineField({
      name: "tags",
      title: "標籤",
      type: "array",
      of: [{ type: "string" }],
      options: { layout: "tags" },
    }),
    defineField({
      name: "showOnHomepage",
      title: "顯示在首頁輪播",
      description: "開啟後，這個作品會自動出現在首頁幻燈片。",
      type: "boolean",
      initialValue: false,
    }),
    defineField({
      name: "homepageOrder",
      title: "首頁輪播排序",
      description: "只有「顯示在首頁輪播」開啟時會出現，數字越小越前面。",
      type: "number",
      hidden: ({ parent }) => !parent?.showOnHomepage,
    }),
    defineField({
      name: "isFeatured",
      title: "設為精選作品",
      type: "boolean",
      initialValue: false,
    }),
    defineField({
      name: "featuredOrder",
      title: "精選排序",
      description: "只有「設為精選作品」開啟時會出現，數字越小越前面。",
      type: "number",
      hidden: ({ parent }) => !parent?.isFeatured,
    }),
    defineField({
      name: "seoTitle",
      title: "SEO 標題",
      type: "string",
    }),
    defineField({
      name: "seoDescription",
      title: "SEO 描述",
      type: "text",
      rows: 3,
    }),
    defineField({
      name: "ogImage",
      title: "社群分享圖片",
      description: "分享連結到社群平台時顯示的圖片。",
      type: "image",
      options: { hotspot: true },
    }),
  ],
  preview: {
    select: {
      title: "title",
      media: "coverImage",
      subtitle: "location",
    },
  },
});
